// ============================================================
//  L.A.B Hub — pages made by your builders. The server's AI team publishes
//  structured page definitions (sections of typed blocks); this module turns
//  the ones YOU added into real sidebar tabs, rendered by trusted templates.
//  No generated HTML ever runs. Links open only http(s) URLs, externally.
// ============================================================
LAB.genpages = {
  list: [],
  installed() { return LAB.store.get('genpages') || []; },
  has(id) { return this.installed().includes(id); },
  add(id) { const ids = this.installed(); if (!ids.includes(id)) { ids.push(id); LAB.store.set('genpages', ids); } this.mount(); },
  remove(id) { LAB.store.set('genpages', this.installed().filter(x => x !== id)); LAB.unregister && LAB.unregister('gen:' + id); this.mount(); },
  async load() { try { const g = await LAB.api('/api/hub/generations'); this.list = g.pages || []; } catch { this.list = []; } this.mount(); return this.list; },
  mount() {
    const ids = this.installed(); let i = 0;
    for (const g of this.list) {
      const id = 'gen:' + g.id;
      if (!ids.includes(g.id)) { if (LAB.pages.some(p => p.id === id)) LAB.unregister(id); continue; }
      const p = g.payload || {};
      LAB.register({ id, label: g.title || g.name || 'Page', icon: I[p.icon] || I.star, order: 20 + i++, generated: true,
        render(el) { LAB.genpages.render(el, g); } });
    }
    LAB.renderNav();
  },
  render(el, g) {
    const p = g.payload || {};
    el.innerHTML = head(g.title || 'Page', (g.summary || '') + (g.agent ? ' · made by ' + LAB.esc(g.agent) : ''));
    for (const s of p.sections || []) {
      const c = LAB.el('div', 'card'); el.appendChild(c);
      const items = Array.isArray(s.items) ? s.items : [];
      let body = '';
      if (s.block === 'text') body = items.map(t => `<p class="gtext">${LAB.esc(t)}</p>`).join('');
      else if (s.block === 'list') body = '<ul class="glist">' + items.map(t => `<li>${LAB.esc(t)}</li>`).join('') + '</ul>';
      else if (s.block === 'steps') body = '<ol class="steps">' + items.map(t => `<li>${LAB.esc(t)}</li>`).join('') + '</ol>';
      else if (s.block === 'metric') body = items.map(it => `<div class="prow"><span>${LAB.esc(it.label)}</span><b>${LAB.esc(it.value)}</b></div>`).join('');
      else if (s.block === 'links') body = items.filter(it => /^https?:\/\//i.test(it.url || '')).map(it => `<div class="prow"><span>${LAB.esc(it.label)}</span><button class="btn" data-url="${LAB.esc(it.url)}">Open</button></div>`).join('');
      else if (s.block === 'checklist') {
        const key = 'gcheck_' + g.id + '_' + (s.heading || ''), done = new Set(LAB.store.get(key) || []);
        body = items.map((t, i) => `<label class="wcheck"><input type="checkbox" data-i="${i}" ${done.has(i) ? 'checked' : ''}><span>${LAB.esc(t)}</span></label>`).join('');
        setTimeout(() => c.querySelectorAll('input').forEach(cb => cb.onchange = () => { const i = +cb.dataset.i; if (cb.checked) done.add(i); else done.delete(i); LAB.store.set(key, [...done]); }));
      }
      c.innerHTML = (s.heading ? `<h3>${LAB.esc(s.heading)}</h3>` : '') + body;
      c.querySelectorAll('[data-url]').forEach(b => b.onclick = () => LAB.openExternal(b.dataset.url));
    }
    el.appendChild(LAB.el('div', 'privacy', 'This tab was generated by your L.A.B builders from what the family actually uses. Remove it any time in the App Store.'));
  }
};
